[env:owl]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = generic_rp2350
framework = arduino
board_build.core = earlephilhower

monitor_speed = 115200
monitor_eol = LF
monitor_echo = yes

board_build.filesystem_size = 0m
board_upload.maximum_size = 2097152

lib_archive = false
build_flags = 
    -D PICO_RP2350A=0

lib_deps =
    askuric/Simple FOC@2.4.0
    simplefoc/SimpleFOCDrivers@1.0.9
